name = "rcm-validation-api"
main = "src/worker.js"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

# Allow workers.dev by default; use env routes on production when zone is ready
workers_dev = true

#############################
# Bindings (shared)
#############################

# Workers AI binding
[ai]
binding = "AI"

# KV Namespaces for data storage (fill IDs after creating resources)
[[kv_namespaces]]
binding = "SURVEY_RESPONSES"
id = "TODO_FILL_SURVEY_RESPONSES_ID"
preview_id = "TODO_FILL_SURVEY_RESPONSES_PREVIEW_ID"

[[kv_namespaces]]
binding = "ANALYTICS_CACHE"
id = "TODO_FILL_ANALYTICS_CACHE_ID"
preview_id = "TODO_FILL_ANALYTICS_CACHE_PREVIEW_ID"

# R2 Bucket for file storage
[[r2_buckets]]
binding = "SURVEY_FILES"
bucket_name = "rcm-survey-files"
preview_bucket_name = "rcm-survey-files-preview"

# D1 Database for structured data
[[d1_databases]]
binding = "SURVEY_DB"
database_name = "rcm_survey_db"
database_id = "TODO_FILL_SURVEY_DB_ID"

# Default environment variables (overridden per env below)
[vars]
ENVIRONMENT = "development"
MAX_DAILY_SUBMISSIONS = "100"
RATE_LIMIT_WINDOW = "3600"
ENABLE_AI_ANALYSIS = "true"
ENABLE_AUDIT_LOGGING = "true"

# Observability
[observability]
enabled = true

# Environment-specific overrides and routes
[env.production]
vars = { ENVIRONMENT = "production" }
route = { pattern = "api.rcm-validation.brainsait.io/*", zone_name = "brainsait.io" }

[env.staging]
vars = { ENVIRONMENT = "staging" }
route = { pattern = "api-staging.rcm-validation.brainsait.io/*", zone_name = "brainsait.io" }

# Optional: Uncomment if using Pages local dev with functions
# pages_build_output_dir = "public"

# Secrets (set via `wrangler secret put` in each env)
# OPENAI_API_KEY
# WEBHOOK_SECRET
# ENCRYPTION_KEY
