name = "rcm-validation-api"
main = "src/worker.js"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
route = { pattern = "api.rcm-validation.brainsait.com/*", zone_name = "brainsait.com" }

[env.staging]
route = { pattern = "api-staging.rcm-validation.brainsait.com/*", zone_name = "brainsait.com" }

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "SURVEY_RESPONSES"
id = "e06355a55a2344aa9e625ad38e8c56ca"
preview_id = "survey_responses_preview"

[[kv_namespaces]]
binding = "ANALYTICS_CACHE"
id = "3cc32643220d42f4a75224d391bb5b3f"
preview_id = "analytics_cache_preview"

# R2 Bucket for file storage (commented out - enable when R2 is available)
# [[r2_buckets]]
# binding = "SURVEY_FILES"
# bucket_name = "rcm-survey-files"
# preview_bucket_name = "rcm-survey-files-preview"

# D1 Database for structured data
[[d1_databases]]
binding = "SURVEY_DB"
database_name = "givc_healthcare_db"
database_id = "f961d236-d309-4e77-a0ae-a4b941293d20"

# Environment variables
[vars]
ENVIRONMENT = "production"
API_VERSION = "2.0"
MAX_DAILY_SUBMISSIONS = "100"
RATE_LIMIT_WINDOW = "3600"
ENABLE_AI_ANALYSIS = "true"
ENABLE_AUDIT_LOGGING = "true"

# Secrets (to be set via wrangler secret put)
# OPENAI_API_KEY = "sk-..."
# WEBHOOK_SECRET = "webhook-secret"
# ENCRYPTION_KEY = "encryption-key"